"""Generate ORACHK.cbl from ADR-0021's hand-derived oracle.

**Why this is a generator and not a hand-written program.** ORACHK's whole job is to check that
GnuCOBOL's `COMPUTE` agrees with a table a human derived by reading the standard. If the table and
the program are maintained separately, a corrected row leaves ORACHK asserting values that no longer
exist -- and it would still report agreement, which is worse than not checking at all.

So the table is the single source and the program is derived from it, with
`tests/unit/test_cobol_oracle_check.py` asserting the committed file is exactly what this script
produces. That is the same drift-check idiom the repo already applies to its JSON schemas.

Run: python tools/cobol-oracle/generate_orachk.py
"""

from __future__ import annotations

import json
from pathlib import Path

ORACLE = (
    Path(__file__).resolve().parents[2]
    / "tests" / "fixtures" / "golden" / "CBACT04C" / "interest-oracle.json"
)
TARGET = Path(__file__).resolve().parent / "ORACHK.cbl"

HEADER = """\
      *****************************************************************
      * GENERATED by tools/cobol-oracle/generate_orachk.py -- do not edit.
      *
      * Checks that GnuCOBOL's own COMPUTE agrees with ADR-0021's
      * hand-derived table, which was produced by a human reading the
      * standard without running any compiler. Two independent
      * derivations agreeing is what turns the dialect risk ADR-0021
      * named from assumed into measured.
      *
      * It COMPARES and sets RETURN-CODE. An earlier version only
      * displayed "expected=X got=Y" and exited 0, so it could not fail
      * however badly the dialect disagreed -- the check-that-cannot-fail
      * pattern, sitting under the one claim the oracle's credibility
      * rests on.
      *****************************************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ORACHK.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  W-BAL    PIC S9(09)V99.
       01  W-RATE   PIC S9(04)V99.
       01  W-INT    PIC S9(09)V99.
       01  W-EXP    PIC S9(09)V99.
       01  W-OUT    PIC -(9)9.99.
       01  W-EXPOUT PIC -(9)9.99.
       01  W-FAILED PIC 9(03) VALUE 0.
       01  W-CHECKS PIC 9(03) VALUE 0.
       PROCEDURE DIVISION.
"""

ROW = """\
           MOVE {balance} TO W-BAL
           MOVE {rate} TO W-RATE
           MOVE {expected} TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH {rid}: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
"""

FOOTER = """\
           DISPLAY "ORACHK: " W-CHECKS " row(s) checked, " W-FAILED
                   " mismatch(es)"
           IF W-FAILED NOT = 0
              DISPLAY "ORACHK: GnuCOBOL disagrees with ADR-0021"
              MOVE 16 TO RETURN-CODE
              STOP RUN
           END-IF
           IF W-CHECKS = 0
              DISPLAY "ORACHK: no rows checked -- the table is empty"
              MOVE 16 TO RETURN-CODE
              STOP RUN
           END-IF
           GOBACK.
"""


def render() -> str:
    rows = json.loads(ORACLE.read_text(encoding="utf-8"))["rows"]
    body = "".join(
        ROW.format(
            rid=row["id"],
            balance=row["balance"],
            rate=row["rate"],
            expected=row["expected"],
        )
        for row in rows
    )
    return HEADER + body + FOOTER


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET} from {ORACLE.name}")
