      *****************************************************************
      * GENERATED by tools/cobol-oracle/generate_orachk.py -- do not edit.
      *
      * Checks that GnuCOBOL's own COMPUTE agrees with ADR-0021's
      * hand-derived table, which was produced by a human reading the
      * standard without running any compiler. Two independent
      * derivations agreeing is what turns the dialect risk ADR-0021
      * named from assumed into measured.
      *
      * It COMPARES and sets RETURN-CODE. An earlier version only
      * displayed "expected=X got=Y" and exited 0, so it could not fail
      * however badly the dialect disagreed -- the check-that-cannot-fail
      * pattern, sitting under the one claim the oracle's credibility
      * rests on.
      *****************************************************************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ORACHK.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  W-BAL    PIC S9(09)V99.
       01  W-RATE   PIC S9(04)V99.
       01  W-INT    PIC S9(09)V99.
       01  W-EXP    PIC S9(09)V99.
       01  W-OUT    PIC -(9)9.99.
       01  W-EXPOUT PIC -(9)9.99.
       01  W-FAILED PIC 9(03) VALUE 0.
       01  W-CHECKS PIC 9(03) VALUE 0.
       PROCEDURE DIVISION.
           MOVE 194.00 TO W-BAL
           MOVE 15.00 TO W-RATE
           MOVE 2.42 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R1: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE -194.00 TO W-BAL
           MOVE 15.00 TO W-RATE
           MOVE -2.42 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R2: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE 100.00 TO W-BAL
           MOVE 25.00 TO W-RATE
           MOVE 2.08 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R3: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE -100.00 TO W-BAL
           MOVE 25.00 TO W-RATE
           MOVE -2.08 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R4: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE 0.50 TO W-BAL
           MOVE 15.00 TO W-RATE
           MOVE 0.00 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R5: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE -0.50 TO W-BAL
           MOVE 15.00 TO W-RATE
           MOVE 0.00 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R6: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE 999.77 TO W-BAL
           MOVE 25.00 TO W-RATE
           MOVE 20.82 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R7: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE -998.33 TO W-BAL
           MOVE 15.00 TO W-RATE
           MOVE -12.47 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R8: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           MOVE 0.00 TO W-BAL
           MOVE 15.00 TO W-RATE
           MOVE 0.00 TO W-EXP
           COMPUTE W-INT = ( W-BAL * W-RATE) / 1200
           ADD 1 TO W-CHECKS
           IF W-INT NOT = W-EXP
              MOVE W-INT TO W-OUT
              MOVE W-EXP TO W-EXPOUT
              DISPLAY "MISMATCH R9: expected" W-EXPOUT " got" W-OUT
              ADD 1 TO W-FAILED
           END-IF
           DISPLAY "ORACHK: " W-CHECKS " row(s) checked, " W-FAILED
                   " mismatch(es)"
           IF W-FAILED NOT = 0
              DISPLAY "ORACHK: GnuCOBOL disagrees with ADR-0021"
              MOVE 16 TO RETURN-CODE
              STOP RUN
           END-IF
           IF W-CHECKS = 0
              DISPLAY "ORACHK: no rows checked -- the table is empty"
              MOVE 16 TO RETURN-CODE
              STOP RUN
           END-IF
           GOBACK.
